#!/usr/bin/env bash
# Run this script once after `cdk deploy CareVaultData CareVaultCompute`.
# It constructs DATABASE_URL from the RDS secret and generates the remaining
# secrets that cannot be auto-generated (correct format required).
#
# Prerequisites: aws CLI, jq, openssl
# Usage: bash infra/scripts/populate-secrets.sh [--profile <aws-profile>]

set -euo pipefail

REGION="af-south-1"
PROFILE_ARG=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile) PROFILE_ARG="--profile $2"; shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

AWS="aws ${PROFILE_ARG} --region ${REGION}"

echo "==> Fetching CloudFormation outputs..."

DB_ENDPOINT=$($AWS cloudformation describe-stacks \
  --stack-name CareVaultData \
  --query "Stacks[0].Outputs[?OutputKey=='DbEndpoint'].OutputValue" \
  --output text)

DB_SECRET_ARN=$($AWS cloudformation describe-stacks \
  --stack-name CareVaultData \
  --query "Stacks[0].Outputs[?OutputKey=='DbSecretArn'].OutputValue" \
  --output text)

echo "    RDS endpoint : ${DB_ENDPOINT}"
echo "    DB secret ARN: ${DB_SECRET_ARN}"

DB_SECRET_JSON=$($AWS secretsmanager get-secret-value \
  --secret-id "${DB_SECRET_ARN}" \
  --query "SecretString" --output text)

DB_USER=$(echo "${DB_SECRET_JSON}" | jq -r '.username')
DB_PASS=$(echo "${DB_SECRET_JSON}" | jq -r '.password')
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_ENDPOINT}:5432/carevault"

echo "==> Populating carevault/prod/database-url..."
$AWS secretsmanager put-secret-value \
  --secret-id "carevault/prod/database-url" \
  --secret-string "${DATABASE_URL}"

echo "==> Generating and populating carevault/prod/encryption-key..."
ENCRYPTION_KEY=$(openssl rand -base64 32)
$AWS secretsmanager put-secret-value \
  --secret-id "carevault/prod/encryption-key" \
  --secret-string "${ENCRYPTION_KEY}"

echo ""
echo "================================================================"
echo "  All required secrets populated."
echo ""
echo "  JWT_SECRET and JWT_REFRESH_SECRET were auto-generated by CDK."
echo "  CRON_SECRET was auto-generated by CDK."
echo ""
echo "  Retrieve the ENCRYPTION_KEY for key-rotation records:"
echo "  aws secretsmanager get-secret-value --secret-id carevault/prod/encryption-key --query SecretString --output text"
echo ""
echo "  Run migrations before the first ECS deployment:"
echo "  DATABASE_URL=\"${DATABASE_URL}\" npm run db:migrate -w @repo/db"
echo "================================================================"
