// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvozzsoufirdxlnnlnky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2b3p6c291ZmlyZHhsbm5sbmt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MDY1ODQsImV4cCI6MjA5MDI4MjU4NH0.yHkTl6-ypsjH_ZxSaUSk9fFiYj7Pq4EFIkPc3v06DIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});